import type { Metadata } from "next";
import "./globals.css";
import { ConfigProvider } from "antd";
import { Clash_Grotesk } from "./fonts/clask-grotesk/ClashGrotesk";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={Clash_Grotesk.className}>
      <body>
        <ConfigProvider theme={{ token: { fontFamily: Clash_Grotesk.style.fontFamily } }}>
          <main>{children}</main>
        </ConfigProvider>
      </body>
    </html>
  );
}
